### ISSUE TITLE
Support for building aws-lc-rs with just rustc 

### ISSUE THREAD

**Issue by rcoh** [aws/aws-lc-rs#152]
### Problem:
We'd love to include aws-lc-rs in the Rust SDK but feel that the current build requirements are too onerous for most customers to use it as the default.

Consider using `build.rs` to replace `CMake` to compile `aws-lc-rs`. Perhaps we could also use the Rust compiler to achieve the static linking achieved with the Go compiler currently?

**Comment by skmcgrail** [comment]
This is potentially doable for the (non-fips) build of aws-lc, as that build doesn't require the use of the Go compiler.

The challenge here would be specific to the static FIPS build, which is what requires the Go compiler. In particular the Go compiler is used to remove relocation entries from the FIPS module boundary of the resulting assembly code. This is done specifically by [delocate](https://github.com/aws/aws-lc/blob/main/util/fipstools/delocate/delocate.go), and more information can be found [here](https://github.com/aws/aws-lc/tree/main/util/fipstools/delocate).

**Comment by pronebird** [comment]
I concur. I've inherited aws-lc-rs through rustls, now I have to walk around 3 platforms we have and tell everyone how to install CMake which is sub-optimal.

**Comment by justsmth** [comment]
> I concur. I've inherited aws-lc-rs through rustls, now I have to walk around 3 platforms we have and tell everyone how to install CMake which is sub-optimal and would rather avoid.

My highest priority right now is eliminating the need for CMake when building for our primary platforms (Linux/MacOS on x86-64/aarch64). Progress is being made. You can watch [this PR](https://github.com/aws/aws-lc-rs/pull/317) for the latest updates.

**Comment by justsmth** [comment]
As of release [v1.7.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.7.0), CMake is no longer required to build **aws-lc-rs** for Linux/MacOS on x86-64/aarch64. For these platforms, only the minimal Rust & C toolchains should be required for the build to succeed.

I'm going to close this issue now. Feel free to open another issue to request extending support for our no-cmake build to other platforms (e.g., Windows).
