### ISSUE TITLE
Linking failures when trying to run on ppc64le architecture due to symbol issues

### ISSUE THREAD

**Issue by skmcgrail** [aws/aws-lc-rs#169]
### Problem:

Attempted to build/test aws-lc-rs on ppc64le architecture, as this architecture is technically supported by AWS-LC.
Besides trying to get this build there is still an outstanding question of what the overall performance profile looks like. This might be a challenge as this build is currently being done in a docker container using qemu.

### Build Notes
* Used fedora:38 docker container using the ppc64le platform image.
* Had to comment out ~4 tests which required use of the ring crate, as ring doesn't appear to support ppc64le?
* When running tests I get a linker error:
```
  = note: /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o): in function `aws_lc_0_7_0_AES_encrypt':
          /home/ec2-user/aws-lc-rs/aws-lc-sys/aws-lc/crypto/fipsmodule/aes/aes.c:64: undefined reference to `aws_lc_0_7_0_aes_hw_encrypt'
          /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o): in function `aws_lc_0_7_0_AES_decrypt':
          /home/ec2-user/aws-lc-rs/aws-lc-sys/aws-lc/crypto/fipsmodule/aes/aes.c:74: undefined reference to `aws_lc_0_7_0_aes_hw_decrypt'
          /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o): in function `aws_lc_0_7_0_AES_set_encrypt_key':
          /home/ec2-user/aws-lc-rs/aws-lc-sys/aws-lc/crypto/fipsmodule/aes/aes.c:87: undefined reference to `aws_lc_0_7_0_aes_hw_set_encrypt_key'
          /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o):(.toc+0x0): undefined reference to `aws_lc_0_7_0_aes_hw_ctr32_encrypt_blocks'
          /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o):(.toc+0x8): undefined reference to `aws_lc_0_7_0_aes_hw_encrypt'
          /usr/bin/ld: /home/ec2-user/aws-lc-rs/target/debug/deps/libaws_lc_sys-32d0dce44c55f186.rlib(bcm.c.o): in function `aws_lc_0_7_0_aes_ctr_set_key':
          /home/ec2-user/aws-lc-rs/aws-lc-sys/aws-lc/crypto/fipsmodule/cipher/e_aes.c:297: undefined reference to `aws_lc_0_7_0_aes_hw_set_encrypt_key'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

warning: `aws-lc-rs` (lib test) generated 3 warnings
error: could not compile `aws-lc-rs` (lib test) due to previous error; 3 warnings emitted
```
* I thought maybe this was due to missing prefix symbols for https://github.com/aws/aws-lc-rs/tree/main/aws-lc-sys/generated-include, but regeneration of these didn't seem to do the trick.
```
 nm libaws_lc_0_7_0crypto.a | grep aes_hw_encrypt
                 U aws_lc_0_7_0_aes_hw_encrypt
00000000000004c0 T aes_hw_encrypt
```

**Comment by Xynnn007** [comment]
Hi @skmcgrail , I met a similar situation to cross-compile ppcle64 on x86-64. If we use `aws-lc-rs` as an underlying crate and use `powerpc64le-linux-gnu-gcc` as linker, there will be same error.


## How to reproduce
```shell
git clone https://github.com/Xynnn007/aws-lc-ppc64le
cd aws-lc-ppc64le && RUSTFLAGS="-C linker=powerpc64le-linux-gnu-gcc" cargo build --release  --target powerpc64le-unknown-linux-gnu
```

Looks like the header files are not found when doing linking?

**Comment by Amulyam24** [comment]
> Hi [@skmcgrail](https://github.com/skmcgrail) , I met a similar situation to cross-compile ppcle64 on x86-64. If we use `aws-lc-rs` as an underlying crate and use `powerpc64le-linux-gnu-gcc` as linker, there will be same error.
> 
> ## How to reproduce
> 
> git clone https://github.com/Xynnn007/aws-lc-ppc64le
> cd aws-lc-ppc64le && RUSTFLAGS="-C linker=powerpc64le-linux-gnu-gcc" cargo build --release  --target powerpc64le-unknown-linux-gnu
> Looks like the header files are not found when doing linking?

Hi @skmcgrail, did you get a chance to look into this issue?
