### ISSUE TITLE
How to use this library with aws-rust-sdk for fips compliance?

### ISSUE THREAD

**Issue by adnan-shoreline** [aws/aws-lc-rs#272]
### Problem:

My application talks to AWS S3 using aws-rust-sdk. I need to make it FIPS compliant. How can I make it use aws-lc-rs and enforce FIPS mode? 

### Solution:

Any guidance and examples would be appreciated. I didn't find any info regarding this on both the aws-rust-sdk and aws-lc-rs repos.

**Comment by adnan-shoreline** [comment]
Or is it sufficient to set environment variable  AWS_USE_FIPS_ENDPOINT to true so that the AWS SDK uses the FIPS endpoints which ensures FIPS compliant algorithms are used? Thanks.

**Comment by skmcgrail** [comment]
Hey @adnan-shoreline, you should create an issue with the [aws-sdk-rust](https://github.com/awslabs/aws-sdk-rust) with regards to getting this question answered for you. The SDK does not currently use aws-lc-rs as its backing cryptographic provider today.

**Comment by adnan-shoreline** [comment]
Created issue at aws-sdk-rust: https://github.com/awslabs/aws-sdk-rust/issues/966
