### ISSUE TITLE
feature request: RSA key generation support

### ISSUE THREAD

**Issue by cpu** [aws/aws-lc-rs#296]
### Problem:

It looks as though aws-lc-rs shares the same API limitation as *ring* with respect to key generation being supported for [EcdsaKeyPair](https://docs.rs/aws-lc-rs/latest/aws_lc_rs/signature/struct.EcdsaKeyPair.html) and [Ed25519KeyPair](https://docs.rs/aws-lc-rs/latest/aws_lc_rs/signature/struct.Ed25519KeyPair.html), but **not** [RsaKeyPair](https://docs.rs/aws-lc-rs/latest/aws_lc_rs/signature/struct.RsaKeyPair.html).

As we're evaluating using aws-lc-rs as [a backend for rcgen](https://github.com/rustls/rcgen/pull/201) it would be really nice if aws-lc-rs supported RSA key generation. There's a class of use-case (e.g. Rustls' integration tests) where we have to use the `openssl` command line in order to generate RSA keypairs. Having support for this in `rcgen` would make replacing that usage feasible.

### Solution:

aws-lc-rs could augment the `RsaKeyPair` struct to offer methods for generating a keypair comparable to those offered by `Ed25519KeyPair` and `EcdsaKeyPair`.

* **Does this change any public APIs?** Yes: the `RsaKeyPair` struct would gain a `generate_pkcs8` and possibly a `generate_pkcs1`  fns.
* **Which algorithm(s) will this impact?** RSA.

### Requirements / Acceptance Criteria:

It must be possible to generate an RSA keypair with both the public and private components. It should be convenient to load the serialized private key using the existing `RsaKeyPair::from_pkcs8` and `RsaKeyPair::from_der` methods. Acceptance should look something like an end-to-end test generating a RSA keypair, loading it, using it to produce a signature, and then verifying the signature.

* **RFC links:** https://www.rfc-editor.org/rfc/rfc8017, https://www.rfc-editor.org/rfc/rfc5208
* **Related Issues:** https://github.com/rustls/rcgen/pull/201, https://github.com/briansmith/ring/issues/219, https://github.com/briansmith/ring/pull/733
* **Will the Usage Guide or other documentation need to be updated?** Yes - API documentation would need updating.
* **Testing:** I expect testing would look similar to the existing Ed25519KeyPair and EcdsaKeyPair key generation test coverage.

**Comment by skmcgrail** [comment]
I have a branch for RSA OAEP support that also adds RSA key generation. I just need to rebase that branch and open a PR for the change.
