### ISSUE TITLE
Remove CMake requirement for builds

### ISSUE THREAD

**Issue by camshaft** [aws/aws-lc-rs#297]
### Problem:

CMake is not a ubiquitous build tool; for example it is not automatically installed with the [build-essential](https://packages.ubuntu.com/focal/build-essential). By requiring CMake, `aws-lc-rs` puts additional build requirements on environments, which will potentially hinder adoption.

### Solution
Instead, the library should have a build system that uses more ubiquitous tools. I think `make` would be a step in the right direction, but I think _ideally_ the only requirement should be a C compiler and assembler. This is the approach that was taken in [s2n-tls-sys](https://github.com/aws/s2n-tls/blob/main/bindings/rust/s2n-tls-sys/build.rs) which makes it quite easy to build.

**Comment by justsmth** [comment]
Related to #152

**Comment by justsmth** [comment]
As of release [v1.7.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.7.0), CMake is no longer required to build **aws-lc-rs** for Linux/MacOS on x86-64/aarch64. For these platforms, only the minimal Rust & C toolchains should be required for the build to succeed.

I'm going to close this issue now. Feel free to open another issue to request extending support for our no-cmake build to other platforms (e.g., Windows).
