### ISSUE TITLE
Please document the licensing of aws-lc

### ISSUE THREAD

**Issue by joshtriplett** [aws/aws-lc-rs#353]
### Problem:

aws-lc-rs lists its license as `SPDX-License-Identifier: ISC AND (Apache-2.0 OR ISC)`, which could lead people to assume that it doesn't have code under the old OpenSSL license. However, https://github.com/aws/aws-lc/blob/main/LICENSE gives a clearer picture of the licensing, showing that aws-lc still has code under the old OpenSSL license. Please document this in the `license` field of `aws-lc-rs` so that, for instance, people looking to preserve GPL-compatibility are not misled into thinking that aws-lc is just ISC and Apache-2.0.

### Solution:

Please modify the `license` field in `Cargo.toml` to also include the OpenSSL license as an `AND`.

**Comment by justsmth** [comment]
Thanks.  I'll follow up on this.

**Comment by justsmth** [comment]
The latest releases of [aws-lc-sys](https://crates.io/crates/aws-lc-sys) and [aws-lc-fips-sys](https://crates.io/crates/aws-lc-fips-sys) have updated license metadata.

**Comment by justsmth** [comment]
See work being done here: https://github.com/aws/aws-lc/pull/3091

We will also be updating the licensing for our -sys crates to align.
