### ISSUE TITLE
Remove NASM requirement for windows builds

### ISSUE THREAD

**Issue by justsmth** [aws/aws-lc-rs#364]
See: aws/aws-lc#1477

**Comment by justsmth** [comment]
There's now a draft PR regarding this issue here: https://github.com/aws/aws-lc-rs/pull/491

Please let us any thoughts/concerns you have on the approach taken for this.

**Comment by justsmth** [comment]
This is resolved with the release of [aws-lc-rs v1.9.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.9.0).

**Comment by camshaft** [comment]
Should we close https://github.com/aws/aws-lc/issues/1477 as well?
