### ISSUE TITLE
Link to guide on bindgen requirement

### ISSUE THREAD

**Issue by camshaft** [aws/aws-lc-rs#366]
### Problem:

Related: https://github.com/aws/s2n-quic/issues/2149

When compiling for a target outside of the pregenerated bindings, the current build fails with a suggestion to enable the bindgen feature in aws-lc-sys. For someone pulling in s2n-quic, this is quite confusing, since they're not depending on it directly.

I think one way to improve this is to link the guide on how to proceed. Maybe we also need to expand the guide a bit and have a specific section about what to do with the dependency of a dependency situation.

Another slight improvement over taking aws-lc as a dependency would be to have them install the [bindgen CLI](https://rust-lang.github.io/rust-bindgen/command-line-usage.html) in their PATH and we could try and detect that and use it instead of the crates.io dependency.

**Comment by justsmth** [comment]
We should link the error message to our [User Guide](https://aws.github.io/aws-lc-rs/index.html), although its [platform support](https://aws.github.io/aws-lc-rs/platform_support.html) section desperately needs updating.  For one, we support many more platforms via bindgen than is indicated there.

> Another slight improvement over taking aws-lc as a dependency would be to have them install the [bindgen CLI](https://rust-lang.github.io/rust-bindgen/command-line-usage.html) in their PATH and we could try and detect that and use it instead of the crates.io dependency.

That's an interesting idea -- the advantage being that it avoids requiring intermediate packages in the dependency chain needing to specify our "bindgen" feature.  We can instruct the consumers facing this issue to install bindgen via `cargo install bindgen-cli`.

**Comment by justsmth** [comment]
This PR links the bindgen error to the User Guide: #369
