### ISSUE TITLE
Plans to aws-lc-fips-sys 0.12.11 release

### ISSUE THREAD

**Issue by samin-cf** [aws/aws-lc-rs#466]
On some Windows machines (specifically Windows-2022 Azure pipeline image), aws-lc-fips-sys fails to compile because the output of vcvarsall.bat isn't fully captured. I have narrowed down the issue to https://github.com/aws/aws-lc-rs/blob/aws-lc-fips-sys/v0.12.10/aws-lc-fips-sys/builder/main.rs#L147.

If I build against my own fork with increased output limit, there are no issues. Seems like @justsmth ran into this as well and updated the max command output limit as part of https://github.com/aws/aws-lc-rs/pull/452.

Would it be possible to do a v0.12.11 release anytime soon that includes @justsmth's changes?

**Comment by justsmth** [comment]
I've got [a PR up](https://github.com/aws/aws-lc-rs/pull/469) for it now.  The release should be very soon.

**Comment by justsmth** [comment]
New version of `aws-lc-fips-sys` released: https://crates.io/crates/aws-lc-fips-sys/0.12.11 

:-)

**Comment by samin-cf** [comment]
Awesome, thank you for the quick response!
