### ISSUE TITLE
Statically linking CRT for aws-lc-fips-sys

### ISSUE THREAD

**Issue by samin-cf** [aws/aws-lc-rs#472]
### Problem:

It would greatly simplify some of our Windows build and installer process if aws-lc-fips-sys supported statically-linking CRT with the `/MT` flag, similar to the aws-lc-sys crate.

In detail, we are distributing aws-lc-fips DLLs that some of the binaries depend on, but they fail to run on systems where VCRUNTIME140.dll is not present. 

### Attempted Solution:

I did try setting `cmake_cfg.static_crt(true)` in aws-lc-fips-sys's `cmake_builder.rs`, but it didn't make a difference. With `cargo build -vvv -p aws-lc-fips-sys`, I saw
```
[aws-lc-fips-sys 0.12.11] cl : Command line warning D9025 : overriding '/MT' with '/MD'
[aws-lc-fips-sys 0.12.11] cl : Command line warning D9002 : ignoring unknown option '-fno-function-sections'
[aws-lc-fips-sys 0.12.11] cl : Command line warning D9002 : ignoring unknown option '-fno-data-sections
```
Something seems to be overriding the /MT flag

**Comment by justsmth** [comment]
I did a little research into this which resulted in [a PR I posted upstream](https://github.com/aws/aws-lc/pull/1737).

As you know, our FIPS build on Windows currently only supports building shared (DLL) libraries. It's important to be aware that there are fundamental problems that can occur when [using static CRT when linking a shared library](https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170#what-problems-exist-if-an-application-uses-more-than-one-crt-version). 
> For example, if a class is allocated in one DLL but passed to and deleted by another, which CRT deallocator is used? The errors caused can range from the subtle to the immediately fatal, and therefore direct transfer of such resources is discouraged.
> ...
> To ensure that all components use the same DLL version of the CRT, build them by using the /MD option, and use the same compiler toolset and property settings.

In `aws-lc-rs`, there are quite a few objects allocated within AWS-LC that [end up being freed by Rust logic](https://github.com/aws/aws-lc-rs/blob/6f3885fc208810b9497b4a51420dac0caece4833/aws-lc-rs/src/ptr.rs#L206-L219).  I don't see any obvious way to avoid potential problems with that build configuration.  

If you're confident and would like to give it a shot anyways, it might be possible to get this to work by [setting `CMAKE_TOOLCHAIN_FILE` in the environment](https://github.com/aws/aws-lc-rs/blob/b9071196c94e4feee29e95cebed7317858b95243/aws-lc-fips-sys/builder/cmake_builder.rs#L141) and configuring specific compile flags to be passed in? I'd be interested if you can find a way to make it work.

**Comment by samin-cf** [comment]
Interesting, thank you looking into this!

To workaround the installer issue, we have been using a custom fork of aws-lc-rs v1.7.1 with aws-lc-fips-sys v0.12.8 where in `aws-lc-fips-sys/CMakeLists.txt`, we explicitly set the cmake policy to CMP0091 and set `CMAKE_MSVC_RUNTIME_LIBRARY` to `MultiThreaded$<$<CONFIG:Debug>:Debug>`. So far, this has been fine (no crashes or memory leaks observed), and we haven't experienced any issues mentioned in that Microsoft doc. Of course, this doesn't mean the problems aren't real, but just providing some reference.

Curious to know, would any potential issues with static CRT be applicable only for `aws-lc-fips-sys` or would they also apply to `aws-lc-sys`?

**Comment by justsmth** [comment]
> We now need to update the version of aws-lc-rs to pull in new features and would like to avoid maintaining a custom fork if possible!

Have you tried creating a CMake "toolchain" configuration file to pass in? I think this would allow setting "CMP0091" and "CMAKE_MSVC_RUNTIME_LIBRARY". This might be more maintainable in the long term.

> Curious to know, would any potential issues with static CRT be applicable only for aws-lc-fips-sys or would they also apply to aws-lc-sys?

I can't think of any issues related to "static CRT" that would different between aws-lc-sys (from AWS-LC's "main" branch) and aws-lc-fips-sys. (The branch of AWS-LC currently used by aws-lc-fips-sys is essentially just a snapshot of our main branch taken sometime around the date of "2022-11-02", with several patches applied to address important issues that have come up.)

**Comment by samin-cf** [comment]
No, I haven't given the toolchain configuration file a try yet but will do so and provide the results!

**Comment by justsmth** [comment]
I'm looking more closely at the places were we transfer memory "ownership" across the API boundary. 

From the places I've checked (such as [here](https://github.com/aws/aws-lc-rs/blob/c8f806c56c8a43a2b89205747d77390001c18b73/aws-lc-rs/src/rsa/encryption/oaep.rs#L303) or [here](https://github.com/aws/aws-lc-rs/blob/5d13428dbbdb227e6c5ff0b4567874e3a3e182ba/aws-lc-rs/src/aead/aead_ctx.rs#L224)), we are using `OPENSSL_malloc` when allocating memory that we will transfer into an AWS-LC struct.  We also don't use [`mem::forget`](https://doc.rust-lang.org/std/mem/fn.forget.html#)) or [`Box::leak`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak) anywhere, so I'm feeling more confident about this being OK.  But we still need to verify that our automated tests are able to catch such an issue if one were introduced.

**Comment by samin-cf** [comment]
Finally got a chance to try the toolchain approach, and I have kind of got it working

This is what I initially had in the toolchain file:
```
if (BUILD_SHARED_LIBS AND FIPS)
    if(POLICY CMP0091)
        cmake_policy(SET CMP0091 NEW)
    endif()
 
    message(STATUS "Setting link to /MTd")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDebug")
endif
```

In the cargo build output, I can see the "Setting link to /MTd" message, but the CMAKE_MSVC_RUNTIME_LIBRARY variable isn't having any effect (tried MultiThreaded and MultiThreaded$<$<CONFIG:Debug>:Debug> as well).

I assume this is because of how [cc-rs](https://github.com/rust-lang/cc-rs/blob/3ba23569a623074748a3030f382afd22483555df/src/lib.rs#L1846) and cmake-rs handle (or rather lack of) the MSVC runtime configuration. They seem to be controlling the MSVC runtime configuration directly using the C[XX] flags.

So, I then tried the following:
```
if (BUILD_SHARED_LIBS AND FIPS)
    message(STATUS "Setting link to /MT")

    set(_re_match "([\\/\\-]M)D")
    set(_re_replace "\\1T")

    # Regex replace /MD -> /MT and -MD -> -MT
    function(replace_flag flag_var)
        if(DEFINED ${flag_var})
            message(STATUS "Original value of ${flag_var}: ${${flag_var}}")
            string(REGEX REPLACE ${_re_match} ${_re_replace} ${flag_var} "${${flag_var}}")
            message(STATUS "New value of ${flag_var}: ${${flag_var}}")
            set(${flag_var} "${${flag_var}}" CACHE STRING "Forcing setting MT" FORCE)
        else()
            message(WARNING "${flag_var} is not defined")
        endif()
    endfunction()

    replace_flag(CMAKE_CXX_FLAGS)
    replace_flag(CMAKE_C_FLAGS)

    # !!! THIS ACTUALLY DOESN'T DO ANYTHING BECAUSE THESE VARIABLES ARE NOT DEFINED
    # !!! WHEN THE TOOLCHAIN FILE IS RUN.
    #
    # replace_flag(CMAKE_C_FLAGS_DEBUG)
    # replace_flag(CMAKE_C_FLAGS_RELEASE)
    # replace_flag(CMAKE_C_FLAGS_MINSIZEREL)
    # replace_flag(CMAKE_C_FLAGS_RELWITHDEBINFO)

    # Manually override from /MD to /MT
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "/MT /Zi /O2 /Ob1 /DNDEBUG" CACHE STRING "Force setting /MT" FORCE)
    set(CMAKE_C_FLAGS_DEBUG "/MTd /Zi /Ob0 /Od /RTC1" CACHE STRING "Force setting /MT" FORCE)
    set(CMAKE_C_FLAGS_MINSIZEREL "/MT /O1 /Ob1 /DNDEBUG" CACHE STRING "Force setting /MT" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "/MT /O2 /Ob2 /DNDEBUG" CACHE STRING "Force setting /MT" FORCE)

endif()
```

This seems to work, but I'd really like to avoid hardcoding the CMAKE_C_FLAGS_[RELWITHDEBUGINFO | DEBUG | MINSIZEREL | RELEASE] flags. For some reason, they aren't defined when the toolchain file is run.

Am I just being dumb and forgetting something obvious 😅?

**Comment by justsmth** [comment]
We recently merged in a [related change for AWS-LC](https://github.com/aws/aws-lc/pull/1737) so we better support `CMAKE_MSVC_RUNTIME_LIBRARY`.  This upstream change will be part of our upcoming aws-lc-rs release. I'm curious whether that change might allow your initial toolchain setup to work?
