### ISSUE TITLE
Failed to build `aws-lc-rs` for FreeBSD x64 due to `rustc` error E0425

### ISSUE THREAD

**Issue by rami3l** [aws/aws-lc-rs#476]
> @justsmth thank you so much for your investigation and hard work so far! I'll see you again very soon in other follow-up issues 😶
_https://github.com/aws/aws-lc-rs/issues/453#issuecomment-2232941539_

Here we go 🤦‍♀️ 

## Problem

After merging https://github.com/rust-lang/rustup/pull/3898, Rustup's FreeBSD CI has started failing.

https://github.com/rust-lang/rustup/pull/3979 tries to set up the necessary dependencies for the build, namely `cmake-core` and `llvm-devel-lite` (for `libclang.so`). Since it's internal bindgen by default, `bindgen-cli` doesn't seem to be required.

But still, `Compiling aws-lc-sys v0.20.1` seems to have failed with the following log:

```rs
  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_LIB_RUST` in this scope
    --> /home/runner/work/rustup/rustup/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.20.1/src/lib.rs:74:14
     |
  74 |     unsafe { ERR_GET_LIB_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^ not found in this scope
  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_REASON_RUST` in this scope
    --> /home/runner/work/rustup/rustup/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.20.1/src/lib.rs:80:14
     |
  80 |     unsafe { ERR_GET_REASON_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^^^^ not found in this scope
  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_FUNC_RUST` in this scope
    --> /home/runner/work/rustup/rustup/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.20.1/src/lib.rs:86:14
     |
  86 |     unsafe { ERR_GET_FUNC_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^^ not found in this scope
  error[E0425]: cannot find function, tuple struct or tuple variant `BIO_ctrl` in this scope
    --> /home/runner/work/rustup/rustup/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.20.1/src/lib.rs:91:14
     |
  91 |     unsafe { BIO_ctrl(b, BIO_CTRL_INFO, 0, pp.cast::<c_void>()) }
     |              ^^^^^^^^ not found in this scope
  error[E0425]: cannot find function, tuple struct or tuple variant `CRYPTO_library_init` in this scope
    --> /home/runner/work/rustup/rustup/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.20.1/src/lib.rs:95:14
     |
  95 |     unsafe { CRYPTO_library_init() }
     |              ^^^^^^^^^^^^^^^^^^^ not found in this scope
  For more information about this error, try `rustc --explain E0425`.
  The following warnings were emitted during compilation:
  warning: aws-lc-sys@0.20.1: CMAKE environment variable set: cmake
  warning: aws-lc-sys@0.20.1: Generating bindings - internal bindgen. Platform: x86_64-unknown-freebsd
  error: could not compile `aws-lc-sys` (lib) due to 5 previous errors
```
_https://github.com/rust-lang/rustup/actions/runs/10192459718/job/28195406529?pr=3979_

## Relevant details

FWIW, we use the following action for our FreeBSD tests:
```yml
- uses: vmactions/freebsd-vm@v1
  with:
    release: 13.2
    usesh: true
    copyback: false
    prepare: |
      pkg install -y git gmake bash sudo cmake-core llvm-devel-lite
```
_https://github.com/rust-lang/rustup/blob/8fdc61316891cdb72acf406b2ac929227ceb0068/ci/actions-templates/freebsd-builds-template.yaml_

**Comment by justsmth** [comment]
Hello again! 😊

I've seen this type of failure before. It typically occurs after the bindings are generated, but the [logic in lib.rs](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-sys/src/lib.rs) fails to pick it up. (Perhaps [this `include!`](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-sys/src/lib.rs#L66) needs an adustment?) I'll dig in now.

**Comment by justsmth** [comment]
Some progress made. I'm able to reproduce the same failure in the FreeBSD CI test I'm setting up: https://github.com/aws/aws-lc-rs/actions/runs/10198121880/job/28212416541#step:3:38543
```
...
      Compiling aws-lc-rs v1.8.1 (/home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-rs)
     Compiling clap_derive v4.5.13
     Compiling clap_builder v4.5.13
  warning: aws-lc-sys@0.20.1: CMAKE environment variable set: cmake
  warning: aws-lc-sys@0.20.1: Generating bindings - internal bindgen. Platform: x86_64-unknown-freebsd
  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_LIB_RUST` in this scope
    --> aws-lc-sys/src/lib.rs:74:14
     |
  74 |     unsafe { ERR_GET_LIB_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^ not found in this scope
  
  error[E0425]: cannot find function, tuple struct or tuple variant `ERR_GET_REASON_RUST` in this scope
    --> aws-lc-sys/src/lib.rs:80:14
     |
  80 |     unsafe { ERR_GET_REASON_RUST(packed_error) }
     |              ^^^^^^^^^^^^^^^^^^^ not found in this scope
...
```

I'm working on setting up a dedicated FreeBSD host so I can debug more easily.

**Comment by justsmth** [comment]
So it appears that the "internal" bindings generation is producing invalid bindings, however using the "external" bindgen-cli works fine and all tests pass:
```
❯ AWS_LC_SYS_EXTERNAL_BINDGEN=1 cargo test -p aws-lc-rs
  Downloaded anstyle-parse v0.2.5
  Downloaded colorchoice v1.0.2
...
warning: aws-lc-sys@0.20.1: CMAKE environment variable set: cmake
warning: aws-lc-sys@0.20.1: Generating bindings - external bindgen. Platform: x86_64-unknown-freebsd
    Finished `test` profile [unoptimized + debuginfo] target(s) in 52.02s
     Running unittests src/lib.rs (target/debug/deps/aws_lc_rs-dcf25f61ef54de42)

running 187 tests
...
test rsa4096_oaep_sha256_mgf1sha256 ... ok
test rsa4096_oaep_sha512_mgf1sha512 ... ok

test result: ok. 37 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.95s

   Doc-tests aws_lc_rs

running 24 tests
test aws-lc-rs/src/cipher.rs - cipher (line 140) ... ok
...
test aws-lc-rs/src/tls_prf.rs - tls_prf (line 8) ... ok
test aws-lc-rs/src/pbkdf2.rs - pbkdf2 (line 23) ... ok

test result: ok. 22 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out; finished in 1.61s
```

So a temporary workaround might be to ensure that "bindgen-cli" is installed and have `AWS_LC_SYS_EXTERNAL_BINDGEN=1` set in the environment. I'll try this for the PR I'm working on for this.

I'll keep digging to see why the internal bindgen is behaving like this.

**Comment by rami3l** [comment]
> So a temporary workaround might be to ensure that "bindgen-cli" is installed and have `AWS_LC_SYS_EXTERNAL_BINDGEN=1` set in the environment.

@justsmth Thanks a lot for the pointers! It seems to work with Rustup as well.
Also, add `rust-bindgen-cli` to the `pkg install -y` line will save you a minute or two from using `cargo install`.

> I'll keep digging to see why the internal bindgen is behaving like this.

Please take your time! It's not really a blocker for us now that we have this workaround :)

**Comment by keehun-cf** [comment]
I've noticed this exact error message when building on Windows 11 using clang/LLVM 19.1.0. As soon as I downgraded to 18.1.8, my builds just started working again.

I'd be happy to create a minimal reproduction case if anyone is interested.

**Comment by keehun-cf** [comment]
I believe we weren't using the external bindgen. I'll see when I will have time to create a minimal repro! I'm hoping that it's straightforward to repro by anyone else as well.

**Comment by justsmth** [comment]
Ok. I reproduced this on my Mac.  Yesterday I updated to llvm v19.1.0, and started seeing these errors when I used the "bindgen" feature.  And when I went back to llvm@18, the problem went away!

So now the questions are: (1) is [rust-bindgen](https://github.com/rust-lang/rust-bindgen) aware of this issue, (2) if so, do they have a fix or workaround; (3) if there's no fix, can we reliably detect whether the build environment is using llvm@19; (4) if so, can we fallback to using `bindgen-cli`?

🤔

**Comment by justsmth** [comment]
After a few iterations of "git bisect" on the rust-bindgen repo, I think I narrowed it down to this commit that fixed the problem when using llvm v19.1: https://github.com/rust-lang/rust-bindgen/commit/600f63895f73c80d6bf7ff3c71b86a068d1663d2

How does that fix it?  I'm not sure.

**Comment by justsmth** [comment]
Possible workarounds: 
* Downgrade LLVM to v18 or earlier.
* Install the latest version of bindgen-cli (`cargo install --force --locked bindgen-cli`) and set AWS_LC_SYS_EXTERNAL_BINDGEN=1 in the build environment.
* Don't enable the "bindgen" feature if not needed for the target platform.

**Comment by justsmth** [comment]
With the release of [bindgen 0.69.5](https://github.com/rust-lang/rust-bindgen/releases/tag/v0.69.5) this problem should now be resolved.  I've also got a [PR](https://github.com/aws/aws-lc-rs/pull/561) up to do some cleanup partially related to this.  It should be part of our next patch release.

Thanks for your patience while getting this resolved!

**Comment by rami3l** [comment]
@justsmth Sorry, did you mean the FreeBSD related issue has been resolved, or the llvm-related one?

**Comment by justsmth** [comment]
@rami3l -- I believe FreeBSD issue was actually just an LLVM 19 issue. 

To verify, I've put up [this PR](https://github.com/aws/aws-lc-rs/pull/561) that removes the "bindgen-cli" installation for the FreeBSD tests. (It also makes it so that FreeBSD can use the "internal" bindgen.) And the CI tests are passing for both FreeBSD 13.4 and 14.1: https://github.com/aws/aws-lc-rs/actions/runs/11241275743/job/31252533681?pr=561 🎉

**Comment by rami3l** [comment]
> @rami3l -- I believe the FreeBSD issue was actually just an LLVM 19 issue. 
> 
> 
> 
> To verify, I've put up [this PR](https://github.com/aws/aws-lc-rs/pull/561) that removes the "bindgen-cli" installation for the FreeBSD tests. (It also makes it so that FreeBSD can use the "internal" bindgen.) And the CI tests are passing for both FreeBSD 13.4 and 14.1: https://github.com/aws/aws-lc-rs/actions/runs/11241275743/job/31252533681?pr=561 🎉
> 
> 
> 
> ```
> 
> ...
> 
>   warning: aws-lc-sys@0.22.0: Building with: CMake
> 
>   warning: aws-lc-sys@0.22.0: Symbol Prefix: Some("aws_lc_0_22_0")
> 
>   warning: aws-lc-sys@0.22.0: CMAKE environment variable set: cmake
> 
>   warning: aws-lc-sys@0.22.0: Clang version: clang version 19.0.0git
> 
>   warning: aws-lc-sys@0.22.0: Generating bindings - internal bindgen. Platform: x86_64-unknown-freebsd
> 
>   warning: aws-lc-sys@0.22.0: Compilation of 'c11.c' succeeded - Ok(["/home/runner/work/aws-lc-rs/aws-lc-rs/target/debug/build/aws-lc-sys-4f788bd60c4b19d9/out/out-c11/89b08a3674570fd2-c11.o"]).
> 
>   warning: aws-lc-sys@0.22.0: Setting CFLAGS: "-O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-2 -fno-omit-frame-pointer -m64 --target=x86_64-unknown-freebsd -std=c11 -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/generated-include -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/include -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/aws-lc/include -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/aws-lc/third_party/s2n-bignum/include -Wall -Wextra -Wno-unused-parameter -DBORINGSSL_IMPLEMENTATION=1 -DBORINGSSL_PREFIX=aws_lc_0_22_0"
> 
>       Finished `test` profile [unoptimized + debuginfo] target(s) in 1m 01s
> 
>        Running unittests src/lib.rs (target/debug/deps/aws_lc_rs-e8cb4d23e3a14b95)
> 
>   
> 
>   running 196 tests
> 
>   test aead::chacha20_poly1305_openssh::tests::derive_poly1305_test ... ok
> 
> ...
> 
> ```

@justsmth Aha, good to hear, and thanks again!
