### ISSUE TITLE
aws-lc-sys build should check for minimal bindgen version

### ISSUE THREAD

**Issue by elmarco** [aws/aws-lc-rs#484]
During the build of a project that depends on rustls, and includes aws-lc-sys:

bindgen-STDERR: error: invalid value '1.59' for '--rust-target <RUST_TARGET>': Got an invalid rust target. Accepted values are of the form "1.0" or "nightly".

I used to have bindgen 0.65.1 installed. 
After upgrading to 0.69.4, issue disappeared.

**Comment by justsmth** [comment]
Hello!  Thanks for reporting this.

I put up a PR to help improve our handling of this: https://github.com/aws/aws-lc-rs/pull/494

**Comment by justsmth** [comment]
This is resolved with the release of [aws-lc-rs v1.9.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.9.0).
