### ISSUE TITLE
1.9.0 compilation fails on old libc (centos) due to atomics missing?

### ISSUE THREAD

**Issue by aviramha** [aws/aws-lc-rs#531]
### Problem:

Latest (1.9.0) causes build failure on old libc machines.
We're using cross + custom base image https://github.com/metalbear-co/ci/blob/main/layer-build/Dockerfile to build and it started failing on the version

I created a simple repro repository here
https://github.com/aviramha/aws-issue-repro

github action that fails:
https://github.com/aviramha/aws-issue-repro/actions/runs/10982117213/job/30489990053

I couldn't reproduce it locally (i'm on M1 macbook so probably Cross doesn't like that..)

**Comment by justinwsmith** [comment]
Hello!

This occurs with older (<= v4.9) versions of the GCC compiler. (Perhaps this happens with older Clang compilers as well?) There was a [change recently made upstream](https://github.com/aws/aws-lc/pull/1824) that should fix this. We plan for this upstream change to be included in our next patch release (aws-lc-rs v1.9.1).

One workaround for this would be to set `AWS_LC_SYS_C_STD=99` in the build environment. (Note that with cross-rs, its build environment does not automatically pick up variables from the host environment. More information about this is [here](https://github.com/cross-rs/cross/blob/main/docs/environment_variables.md).)

Let us know if this workaround, or the next patch release, doesn't fix this issue. Thanks!

**Comment by aviramha** [comment]
Hey @justinwsmith 
Kudos for the swift reply! I am happy to hear this is already known and will be fixed next patch release.

We'd wait for that instead of going with the workaround as there's no urgency from our side (and I appreciate you going into the details and quirks of cross who I unfortunately already know 🤣 )

**Comment by justsmth** [comment]
I believe this issue is resolved with the release of [aws-lc-sys v1.10.0](https://github.com/aws/aws-lc-rs/releases/tag/v1.10.0). Please feel free to reopen if you're still experiencing this issue after upgrading. Thanks for helping us improve aws-lc-rs!
