### ISSUE TITLE
how can I solve this issue

### ISSUE THREAD

**Issue by WZY2317** [aws/aws-lc-rs#637]
#Consider installing NASM or setting `AWS_LC_SYS_PREBUILT_NASM` in the build environment.See User Guide: https://aws.github.io/aws-lc-rs/index.html
  Missing dependency: nasm
  Missing dependency: cmakeConsider installing NASM or setting `AWS_LC_SYS_PREBUILT_NASM` in the build environment.See User Guide: https://aws.github.io/aws-lc-rs/index.html
  Missing dependency: nasm
  Missing dependency: cmake

**Comment by justsmth** [comment]
Hello!

We provide guidance in our [User Guide](https://aws.github.io/aws-lc-rs/index.html) on how to install NASM here: https://aws.github.io/aws-lc-rs/requirements/windows.html#nasm
